name: Build ttf-menomonia

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  dist-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fontforge python3-fonttools

      - name: Dist
        run: |
          make dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: menomonia-fonts-*.tar.gz
